# === AWS Transmutation Pipeline Configuration File ===
#
# See https://github.com/MarcGuiselin/aws-transmutation for documentation
#
# WARNING: Currently changing this file might break transmutation pipeline! Delete
#          your pipeline's stack, edit this file, push changes, and then you can
#          create a new pipeline.

# Default settings for all branch pipelines
enabled = true
stage = "test" # typically prod or test
features = "Build > Deploy > Integration"
description = "A test deployment"
# Runs cleanup and then deletes the pipeline and its stack after their branch is deleted. False by default.
delete_old_pipeline = true

# Default file locations (relative to repo root)
[file_paths]
template_configuration = "aws/test-configuration.json"
build_spec = "build.yaml"
deploy_spec = "deploy.yaml"
integ_spec = "integ.yaml"

# Default compute environment used for scripts
# See https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html
# and https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
[environment]
type = "LINUX_CONTAINER"
compute = "BUILD_GENERAL1_SMALL"
image = "aws/codebuild/amazonlinux2-x86_64-standard:3.0"

# Production Deployment
[[pipeline]]
branch = "master"
stage = "prod"
stack = "my-transmutation-starter-master-stack" # Override stack name for master deployment
features = "Build > Deploy"
description = "The production deployment"
delete_old_pipeline = false # Override delete_old_pipeline for master deployment pipeline
  [pipeline.file_paths]
  template_configuration = "aws/prod-configuration.json"

# Bors-NG staging and trying branches should be built
[[pipeline]]
branch = "staging|trying"
description = "Test deployments for Bors-NG"

# Bors-NG *.tmp branches should not be built
[[pipeline]]
enabled = false
branch = "*.tmp"